# -*- coding: utf-8 -*-
"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.8.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from django.conf.global_settings import TEMPLATE_CONTEXT_PROCESSORS as TCP

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'p1p2e^77+6ex*1@-s6hzcx7l3bx#g2q0w1za1c-x-1p@n6z^x*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',

    'blog',
    'vmaig_auth',
    'vmaig_comments',
    'vmaig_system'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'vmaig_blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates/")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vmaig_blog.wsgi.application'

TEMPLATE_CONTEXT_PROCESSORS = TCP + (
    'django.core.context_processors.request',
)

SUIT_CONFIG = {
    'ADMIN_NAME': u'个人博客管理平台',
    'HEADER_DATE_FORMAT': 'Y年 F j日 l',
    'LIST_PER_PAGE': 20,
    # 'MENU_EXCLUDE': ('auth.group',),
    'MENU': (
        {'label': u'博客管理', 'icon': 'icon-folder-open', 'models': (
            {'model': 'blog.Nav', 'label': u'导航条'},
            {'model': 'blog.Category', 'label': u'分类管理'},
            {'model': 'blog.Article', 'label': u'文章管理'},
            {'model': 'blog.Column', 'label': u'专栏管理'},
            {'model': 'blog.Carousel', 'label': u'轮播管理'},
            {'model': 'blog.News', 'label': u'资讯管理'},
        )},
        # # {'app': 'engine', 'label': u'文件中心', 'icon': 'icon-file',},
        {'label': u'评论管理', 'icon': 'icon-file', 'models': (
            {'model': 'vmaig_comments.Comment', 'label': u'评论管理'},
        )},

        {'label': u'权限管理', 'icon': 'icon-file', 'models': (
            {'model': 'vmaig_auth.VmaigUser', 'label': u'用户管理'},
        )},

        {'label': u'系统管理', 'icon': 'icon-file', 'models': (
            {'model': 'vmaig_system.Notification', 'label': u'用户管理'},
            {'model': 'vmaig_system.Link', 'label': u'友情链接'},
        )},

        # #
        # # {'app': 'workload', 'label': u'预算管理', 'icon': 'icon-tasks',},
        # #
        # {'label': u'图例管理', 'icon': 'icon-leaf', 'models': (
        #     {'model': 'legend.legend', 'label': u'基本图例'},
        # )},
        # '-',
        # #
        # {'label': u'预算数据', 'icon': 'icon-asterisk', 'models': (
        #     {'model': 'legend.quotaworkload', 'label': u'定额编号'},
        #     {'model': 'legend.constructionm', 'label': u'工程机械'},
        #     {'model': 'legend.instrument', 'label': u'仪器仪表'},
        #     {'model': 'legend.lineworkload', 'label': u'主设线材'},
        # )},
        #
        # {'label': u'导线器材', 'icon': 'icon-asterisk', 'models': (
        #     {'model': 'wire.WireBase', 'label': u'导线配置'},
        #     {'model': 'wire.Specification', 'label': u'导线规格'},
        #     {'model': 'wire.Supplier', 'label': u'供应商'},
        #     {'model': 'workload.WireDetailTable', 'label': u'导线明细'},
        #     {'model': 'workload.RouteType', 'label': u'导线类型'},
        # )},
        #
        # {'label': u'基础数据', 'icon': 'icon-asterisk', 'models': (
        #     {'model': 'legend.units', 'label': u'单位配置'},
        #     {'model': 'legend.property', 'label': u'属性配置'},
        #     {'model': 'legend.typeline', 'label': u'类型配置'},
        # )},
        #
        # {'label': u'默认数据', 'icon': 'icon-asterisk', 'models': (
        #     {'model': 'workload.DefaultData', 'label': u'默认预算'},
        #     {'model': 'workload.DefaultCM', 'label': u'工程机械'},
        #     {'model': 'workload.defaultinstrument', 'label': u'仪器仪表'},
        # )},
        # '-',
        # {'label': u'算法管理', 'icon': 'icon-tasks', 'models': (
        #     {'model': 'algorithm.sheet2algorithm', 'label': u'建筑安装工程费用预算表算法(表二)'},
        #     {'model': 'algorithm.TypeLineAlgorithm', 'label': u'国内器材算法管理(表四甲)'},
        #     {'model': 'legend.QuotaAlgorithm', 'label': u'定额算法管理'},
        # )},
        # '-',
        # {'label': u'用户管理', 'icon': 'icon-user', 'models': (
        #     {'model': 'user.region', 'label': u'区域管理'},
        #     {'model': 'user.myuser', 'label': u'用户管理'},
        # )},
        #
        # {'label': u'权限管理', 'icon': 'icon-lock', 'models': (
        #     {'model': 'auth.user', 'label': u'用户'},
        #     {'model': 'auth.group', 'label': u'权限组'},
        #     {'model': 'auth.permission', 'label': u'权限'},
        # )},
        #
        # {'label': u'文档管理', 'icon': 'icon-file', 'models': (
        #     # {'model': 'document.Blog', 'label': u'文档管理'},
        #     {'model': 'document.DocType', 'label': u'文档分类'},
        #     {'model': 'document.Document', 'label': u'文章列表'},
        #     {'model': 'filer.file', 'label': u'文件列表'},
        # )},
    )
}

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

if DEBUG:
    HOST = '192.168.1.107'
    DB_NAME = 'vmaig_blog'
    DB_USER = 'root'
    DB_PWD = 'root'
else:
    HOST = '121.42.178.20'
    DB_NAME = 'junxinda'
    DB_USER = 'root'
    DB_PWD = 'xxxxxxx'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PWD,
        'HOST': HOST,
        'PORT': '3306',
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-cn'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'static_root'

# 设置user model
AUTH_USER_MODEL = "vmaig_auth.VmaigUser"


# log配置
LOG_FILE = "./all.log"

LOGGING = {
        'version': 1,
        'disable_existing_loggers': True,

        'filters': {
            'require_debug_false': {
                '()': 'django.utils.log.RequireDebugFalse'
                }
            },
        'formatters': {
            'simple': {
                'format': '[%(levelname)s] %(module)s : %(message)s'
                },
            'verbose': {
                'format':
                    '[%(asctime)s] [%(levelname)s] %(module)s : %(message)s'
                }
            },

        'handlers': {
            'null': {
                'level': 'DEBUG',
                'class': 'django.utils.log.NullHandler',
                },
            'console': {
                'level': 'INFO',
                'class': 'logging.StreamHandler',
                'formatter': 'verbose'
                },
            'file': {
                'level': 'INFO',
                'class': 'logging.FileHandler',
                'formatter': 'verbose',
                'filename': LOG_FILE,
                'mode': 'a',
                },
            'mail_admins': {
                'level': 'ERROR',
                'class': 'django.utils.log.AdminEmailHandler',
                'filters': ['require_debug_false']
                }
            },
        'loggers': {
            '': {
                'handlers': ['file', 'console'],
                'level': 'INFO',
                'propagate': True,
                },
            'django': {
                'handlers': ['file', 'console'],
                'level': 'DEBUG',
                'propagate': True,
                },
            'django.request': {
                'handlers': ['mail_admins', 'console'],
                'level': 'ERROR',
                'propagate': True,
                },
            }
        }


# cache配置
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'options': {
            'MAX_ENTRIES': 1024,
        }
    },
    'memcache': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        # 'LOCATION': 'unix:/home/billvsme/memcached.sock',
        'LOCATION': '127.0.0.1:11211',
        'options': {
            'MAX_ENTRIES': 1024,
        }
    },
}


# 分页配置
PAGE_NUM = 5

# email配置
# 如果想要支持ssl (比如qq邮箱) 见 https://github.com/bancek/django-smtp-ssl
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = ''                       # SMTP地址 例如: smtp.163.com
EMAIL_PORT = 25                       # SMTP端口 例如: 25
EMAIL_HOST_USER = ''                  # 我自己的邮箱 例如: xxxxxx@163.com
EMAIL_HOST_PASSWORD = ''              # 我的邮箱密码 例如  xxxxxxxxx
EMAIL_SUBJECT_PREFIX = u'vmaig'       # 为邮件Subject-line前缀,默认是'[django]'
EMAIL_USE_TLS = True                  # 与SMTP服务器通信时，是否启动TLS链接(安全链接)。默认是false

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# 七牛配置
QINIU_ACCESS_KEY = ''
QINIU_SECRET_KEY = ''
QINIU_BUCKET_NAME = ''

# 网站标题等内容配置
WEBSITE_TITLE = u'Vmaig'
WEBSITE_WELCOME = u'欢迎来到Vmaig'

